mkdir $HOME/jars
cd $HOME/jars
wget http://repo1.maven.org/maven2/joda-time/joda-time/2.0/joda-time-2.0.jar
wget http://repo1.maven.org/maven2/org/codehaus/jettison/jettison/1.3.1/jettison-1.3.1.jar
wget http://repo1.maven.org/maven2/org/yaml/snakeyaml/1.6/snakeyaml-1.6.jar
wget http://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1/json-simple-1.1.jar
wget http://repo1.maven.org/maven2/org/mortbay/jetty/jetty/6.1.22/jetty-6.1.22.jar
wget http://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.6.1/libthrift-0.6.1.jar
wget http://repo1.maven.org/maven2/com/github/stephenc/eaio-uuid/uuid/3.2.0/uuid-3.2.0.jar
wget http://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
wget http://repo1.maven.org/maven2/com/github/stephenc/high-scale-lib/high-scale-lib/1.1.1/high-scale-lib-1.1.1.jar
wget http://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.jar
wget http://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar
wget http://repo1.maven.org/maven2/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
wget http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
wget http://repo1.maven.org/maven2/com/ning/compress-lzf/0.8.4/compress-lzf-0.8.4.jar
wget http://repo1.maven.org/maven2/stax/stax-api/1.0.1/stax-api-1.0.1.jar
wget http://repo1.maven.org/maven2/org/apache/cassandra/deps/avro/1.4.0-cassandra-1/avro-1.4.0-cassandra-1.jar
wget http://repo1.maven.org/maven2/com/google/guava/guava/11.0.2/guava-11.0.2.jar
wget http://repo1.maven.org/maven2/org/antlr/antlr/3.2/antlr-3.2.jar
wget http://antlr.org/antlr-snapshot/antlr/antlr/2.7.7/antlr-2.7.7.jar
wget http://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar
wget http://repo1.maven.org/maven2/junit/junit/4.4/junit-4.4.jar
wget http://repo1.maven.org/maven2/org/apache/cassandra/cassandra-all/1.0.8/cassandra-all-1.0.8.jar
wget http://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar
wget http://repo1.maven.org/maven2/com/github/stephenc/jamm/0.2.5/jamm-0.2.5.jar
wget http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar
wget http://repo1.maven.org/maven2/commons-cli/commons-cli/1.1/commons-cli-1.1.jar
wget http://repo1.maven.org/maven2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.commons-csv/1.0-r706900_3/org.apache.servicemix.bundles.commons-csv-1.0-r706900_3.jar
wget http://repo1.maven.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
wget http://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.4.0/jackson-mapper-asl-1.4.0.jar
wget http://repo1.maven.org/maven2/com/3363googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.2/concurrentlinkedhashmap-lru-1.2.jar
wget http://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
wget http://repo1.maven.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.jar
wget http://download.java.net/maven/2/org/mortbay/jetty/jetty-util/6.1.22/jetty-util-6.1.22.jar
wget http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar
wget http://download.java.net/maven/1/org.mortbay.jetty/jars/jetty-util-6.1.22.jar
wget http://repo1.maven.org/maven2/org/mortbay/jetty/jetty-util/6.1.22/jetty-util-6.1.22.jar
wget http://antlr.org/antlr-snapshot/org/antlr/antlr-runtime/3.2/antlr-runtime-3.2.jar
wget http://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar
wget http://repo1.maven.org/maven2/org/apache/cassandra/cassandra-thrift/1.0.8/cassandra-thrift-1.0.8.jar
wget http://repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.4.0/jackson-core-asl-1.4.0.jar
wget http://download.java.net/maven/2/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.jar
wget http://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.2/antlr-runtime-3.2.jar
wget http://download.java.net/maven/1/org.mortbay.jetty/jars/servlet-api-2.5-20081211.jar
wget http://antlr.org/antlr-snapshot/org/antlr/stringtemplate/3.2/stringtemplate-3.2.jar
wget http://repo1.maven.org/maven2/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.jar
wget http://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2/stringtemplate-3.2.jar
wget http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
wget http://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/1.2/maven-common-artifact-filters-1.2.jar
wget http://repo1.maven.org/maven2/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar
wget http://repo1.maven.org/maven2/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
wget http://repo1.maven.org/maven2/com/netflix/astyanax/astyanax/1.0.4/astyanax-1.0.4.jar
